#!/bin/bash

if [ -z "$1" ]; then
  echo "error: thruster index not specified"
  exit 1
fi

npubs=2
sleeptime=0.25
force=2
start=$1
end=$1
if [ ! -z "$2" ]; then
  force=$2
fi

if [ "$1" = "all" ]; then
  start=0
  end=7
fi

for ((t=$start; t<=$end; t++)); do
  for ((i=0; i<$npubs; i++)); do 
    ros2 topic pub -1 /barracuda/thrusters/input$t std_msgs/msg/Float32 "{data: $force}" 
  done
done