services:
  barracuda-thrusters:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    user: root
    privileged: true
    image: barracuda-thrusters
    container_name: barracuda-thrusters
    tty: true
    network_mode: host
    ipc: host
    volumes:
      - ${HOME}/.ssh:/root/.ssh
  barracuda-thrusters-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    user: root
    privileged: true
    image: barracuda-thrusters-dev
    container_name: barracuda-thrusters-dev
    tty: true
    network_mode: host
    ipc: host
    volumes:
      - ${HOME}/.ssh:/root/.ssh
      - ${HOME}/.gitconfig:/root/.gitconfig
      - ${HOME}/.vimrc:/root/.vimrc
      - ../barracuda_thrusters:/ros2_ws/src/barracuda_thrusters
    profiles: ["dev"]
